title   : Kodemon
email   : hi@kodemon.net
url     : "https://www.kodemon.net" # the base hostname & protocol for your site, e.g. http://example.com
baseurl : "" # the subpath of your site, e.g. /blog

github_username: kodemon

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
